name: 'setup vppcfg action'
description: 'Setup vppcfg'
inputs:
  vppcfg-ref:
    description: "Ref of vppcfg to install"
    required: false
    default: "main"
  install-source:
    description: "Install from 'pypi' or 'source'"
    required: true
    default: "pypi"
runs:
  using: "composite"
  steps:
    - name: Install vppcfg from source
      shell: bash
      if: "inputs.install-source == 'source'"
      run: |-
        origdir="$(pwd)"
        pip instal vppcfg==$VPPCFGREF
        python3 -m venv .venv
        source .venv/bin/activate
        make install-deps
        make test
        make build
        deactivate
        make install
        vppcfg -h
        
        cd "$origdir"
        rm -rf /tmp/vppcfg
      env:
        VPPCFGREF: ${{ inputs.vppcfg-ref }}

    - name: Install vppcfg from pypi
      shell: bash
      if: "inputs.install-source == 'pypi'"
      run: |-
        pip install vppcfg==$VPPCFGVER
      env:
        VPPCFGVER: ${{ inputs.vppcfg-ref }}
